name: Build and Push Docker Image
on:
  release:
    types:
      'published'

jobs:
  build:
    name: Build and Push Docker Image
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - latest
          - ${{ github.ref_name }}

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: termider
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/iut-terminder/${{ github.event.repository.name }}:${{ matrix.versions }}
